### ISSUE TITLE
Support for asyncpg 0.26.0?

### ISSUE THREAD

**Issue by ps-george** [bryanforbes/asyncpg-stubs#109]
Hey @bryanforbes, really appreciate this library.

Would be very useful to have a 0.26.0 release out, even if it's just 0.25.4 in disguise but without the `depends on asyncpg<0.26.0`.

Watching your PR on the main lib too with 😍 https://github.com/MagicStack/asyncpg/pull/577. Many thanks for your efforts

**Comment by bryanforbes** [comment]
Yes, I plan to do an update for 0.26.0. Hopefully this week if I have the time.

**Comment by bryanforbes** [comment]
The changes were pretty simple and I had a few spare minutes. You'll find v0.26.0 on pypi.

**Comment by ps-george** [comment]
Just saw this on our dependabots, thank you 🙌

**Comment by ps-george** [comment]
@bryanforbes haven't got another comms channel to you, but been using this a lot and wanted to express some more appreciation for the timely response! Thanks so much 🏆
